- name: Deploy to EC2
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      mkdir -p ~/app
      cd ~/app

      # Pull latest code
      if [ ! -d ".git" ]; then
        git clone https://github.com/${{ github.repository }} . 
      else
        git reset --hard
        git pull origin main
      fi

      # Build & run containers
      docker compose down || true
      docker compose up -d --build
    EOF
