version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=sqlite:///./dev.db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '5173:80'
    command: npx serve -s dist -l 80
    volumes:
      - ./frontend:/app

