name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend build
      - name: Build backend image
        run: |
          docker build -t backend:test ./backend

      # Frontend build
      - name: Build frontend image
        run: |
          docker build -t frontend:test ./frontend

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build   # deploy runs only if build succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            mkdir -p ~/app
            cd ~/app

            # Pull latest code
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} . 
            else
              git reset --hard
              git pull origin main
            fi

            # Build & run containers (Compose v2 syntax)
            docker compose down || true
            docker compose up -d --build
          EOF
