name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app || mkdir -p ~/app && cd ~/app

            # Pull latest code
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} . 
            else
              git reset --hard
              git pull origin main
            fi

            # Build & run containers
            docker-compose down || true
            docker-compose up -d --build
          EOF
