name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t backend:test ./backend
      - run: docker build -t frontend:test ./frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            set -e
            mkdir -p ~/app
            cd ~/app
            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git reset --hard
              git pull origin main
            fi
            docker-compose down || true
            docker-compose up -d --build
          "
